import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: {
        padding: 36,
        backgroundColor: '#ffffff',
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 6,
    },
    title: {
        fontSize: 22,
        fontFamily: 'Helvetica-Bold',
        color: '#111111',
    },
    subtitle: {
        fontSize: 10,
        color: '#888888',
        marginTop: 4,
    },
    divider: {
        borderBottomWidth: 1.5,
        borderBottomColor: '#111111',
        marginVertical: 12,
    },
    movieRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#eeeeee',
    },
    left: {
        flexDirection: 'row',
        flex: 1,
    },
    index: {
        width: 22,
        fontSize: 9,
        color: '#aaaaaa',
        paddingTop: 1,
    },
    movieInfo: {
        flex: 1,
    },
    movieTitle: {
        fontSize: 11,
        fontFamily: 'Helvetica-Bold',
        color: '#111111',
    },
    movieDetails: {
        fontSize: 8.5,
        color: '#666666',
        marginTop: 2,
    },
    rating: {
        fontSize: 10,
        color: '#e67e22',
        fontFamily: 'Helvetica-Bold',
        marginLeft: 8,
        paddingTop: 1,
    },
    footer: {
        position: 'absolute',
        bottom: 24,
        left: 36,
        right: 36,
        fontSize: 8,
        color: '#cccccc',
        textAlign: 'center',
    },
    emptyText: {
        fontSize: 12,
        color: '#aaaaaa',
        marginTop: 20,
        textAlign: 'center',
    },
});

const DownloadList = ({ movies = [], listTitle = 'My List' }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>{listTitle}</Text>
                <Text style={styles.subtitle}>
                    {movies.length} {movies.length === 1 ? 'movie' : 'movies'} — JAS Movies
                </Text>
            </View>

            <View style={styles.divider} />

            {movies.length === 0 ? (
                <Text style={styles.emptyText}>No movies in this list.</Text>
            ) : (
                movies.map((movie, index) => (
                    <View key={movie.title} style={styles.movieRow}>
                        <View style={styles.left}>
                            <Text style={styles.index}>{index + 1}.</Text>
                            <View style={styles.movieInfo}>
                                <Text style={styles.movieTitle}>{movie.title}</Text>
                                <Text style={styles.movieDetails}>
                                    {movie.director} • {movie.genre} • {movie.releasing_year} • {movie.age_group} • {movie.language}
                                </Text>
                            </View>
                        </View>
                        <Text style={styles.rating}>{movie.imdb_rating}/10</Text>
                    </View>
                ))
            )}

            <Text style={styles.footer}>Generated by JAS Movies</Text>
        </Page>
    </Document>
);

export default DownloadList;
